Repository Tianea2160/daldal, pull requests merged in 2023-03, with the labels that each got.

#2 mongo 세팅 및 Login api 구현
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/com/beside/daldal/config/JpaConfig.kt
  src/main/kotlin/com/beside/daldal/config/MongoConfig.kt
  src/main/kotlin/com/beside/daldal/config/SecurityConfig.kt
  src/main/kotlin/com/beside/daldal/config/SwaggerConfig.kt
  src/main/kotlin/com/beside/daldal/domain/auth/controller/AuthController.kt
  src/main/kotlin/com/beside/daldal/domain/auth/dto/TokenRequestDTO.kt
  src/main/kotlin/com/beside/daldal/domain/auth/dto/TokenResponseDTO.kt
  src/main/kotlin/com/beside/daldal/domain/auth/error/BearerTokenIsNotRefreshToken.kt
  src/main/kotlin/com/beside/daldal/domain/auth/error/JwtNotFoundException.kt
  src/main/kotlin/com/beside/daldal/domain/auth/service/AuthService.kt
  src/main/kotlin/com/beside/daldal/domain/auth/service/CustomUserDetailService.kt
  src/main/kotlin/com/beside/daldal/domain/course/controller/CourseController.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseComplexDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseCreateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseReadDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseUpdateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/entity/Course.kt
  src/main/kotlin/com/beside/daldal/domain/course/error/CourseAuthorizationException.kt
  src/main/kotlin/com/beside/daldal/domain/course/error/CourseNotFoundException.kt
  src/main/kotlin/com/beside/daldal/domain/course/repository/CourseRepository.kt
  src/main/kotlin/com/beside/daldal/domain/course/service/CourseService.kt
  src/main/kotlin/com/beside/daldal/domain/member/dto/MemberCreateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/member/dto/MemberLoginDTO.kt
  src/main/kotlin/com/beside/daldal/domain/member/dto/MemberReadDTO.kt
  src/main/kotlin/com/beside/daldal/domain/member/entity/LoginType.kt
  src/main/kotlin/com/beside/daldal/domain/member/entity/Member.kt
  src/main/kotlin/com/beside/daldal/domain/member/error/MemberNotFoundException.kt
  src/main/kotlin/com/beside/daldal/domain/member/repository/MemberRepository.kt
  src/main/kotlin/com/beside/daldal/domain/member/service/MemberService.kt
  src/main/kotlin/com/beside/daldal/jwt/JwtAccessDeniedHandler.kt
  src/main/kotlin/com/beside/daldal/jwt/JwtAuthenticationEntryPoint.kt
  src/main/kotlin/com/beside/daldal/jwt/JwtFilter.kt
  src/main/kotlin/com/beside/daldal/jwt/JwtSecurityConfig.kt
  src/main/kotlin/com/beside/daldal/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/beside/daldal/shared/dto/CommonResponse.kt
  src/main/kotlin/com/beside/daldal/shared/entity/BaseTimeEntity.kt
  src/main/kotlin/com/beside/daldal/shared/exception/dto/DaldalRuntimeException.kt
  src/main/kotlin/com/beside/daldal/shared/exception/dto/ErrorCode.kt
  src/main/kotlin/com/beside/daldal/shared/exception/handler/GlobalExceptionHandler.kt
Labels: enhancement

#4 도메인 entity 개선 및 course api 수정
  Dockerfile
  docker-compose.yml
  src/main/kotlin/com/beside/daldal/domain/comment/entity/Comment.kt
  src/main/kotlin/com/beside/daldal/domain/course/controller/CourseController.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseComplexDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseCreateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseReadDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseUpdateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/entity/Course.kt
  src/main/kotlin/com/beside/daldal/domain/course/repository/CourseRepository.kt
  src/main/kotlin/com/beside/daldal/domain/course/service/CourseService.kt
  src/main/kotlin/com/beside/daldal/domain/member/entity/Member.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/Review.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/ReviewFeature.kt
Labels: enhancement

#10 파일 업로드 및 네이버 감정 분석 AI 연동 완료
  build.gradle.kts
  src/main/kotlin/com/beside/daldal/config/AwsS3Config.kt
  src/main/kotlin/com/beside/daldal/config/WebClientConfig.kt
  src/main/kotlin/com/beside/daldal/domain/image/error/ImageDeleteFailException.kt
  src/main/kotlin/com/beside/daldal/domain/image/error/ImageUploadFailException.kt
  src/main/kotlin/com/beside/daldal/domain/image/service/ImageService.kt
  src/main/kotlin/com/beside/daldal/domain/sentiment/dto/SentimentRequest.kt
  src/main/kotlin/com/beside/daldal/domain/sentiment/dto/SentimentResponse.kt
  src/main/kotlin/com/beside/daldal/domain/sentiment/error/SentimentAnalyzeFailException.kt
  src/main/kotlin/com/beside/daldal/domain/sentiment/error/SentimentMaxLengthException.kt
  src/main/kotlin/com/beside/daldal/domain/sentiment/service/SentimentService.kt
Labels: enhancement

#9 review, comment domain 구현
  src/main/kotlin/com/beside/daldal/domain/comment/dto/CommentDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseComplexDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/service/CourseService.kt
  src/main/kotlin/com/beside/daldal/domain/favourite/controller/FavouriteController.kt
  src/main/kotlin/com/beside/daldal/domain/favourite/entity/Favourite.kt
  src/main/kotlin/com/beside/daldal/domain/favourite/error/FavouriteAlreadyExistException.kt
  src/main/kotlin/com/beside/daldal/domain/favourite/error/FavouriteNotFoundException.kt
  src/main/kotlin/com/beside/daldal/domain/favourite/repository/FavoriteRepository.kt
  src/main/kotlin/com/beside/daldal/domain/favourite/service/FavouriteService.kt
  src/main/kotlin/com/beside/daldal/domain/image/error/ImageNotFoundException.kt
  src/main/kotlin/com/beside/daldal/domain/image/error/ImageTypeException.kt
  src/main/kotlin/com/beside/daldal/domain/image/service/ImageService.kt
  src/main/kotlin/com/beside/daldal/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/beside/daldal/domain/review/dto/ReviewCreateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/review/dto/ReviewDTO.kt
  src/main/kotlin/com/beside/daldal/domain/review/dto/ReviewReadDTO.kt
  src/main/kotlin/com/beside/daldal/domain/review/dto/ReviewUpdateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/review/dto/ReviewsDTO.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/Review.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/ReviewFeature.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/ReviewSentiment.kt
  src/main/kotlin/com/beside/daldal/domain/review/error/ReviewAuthorizationException.kt
  src/main/kotlin/com/beside/daldal/domain/review/error/ReviewNotFoundException.kt
  src/main/kotlin/com/beside/daldal/domain/review/repository/CustomReviewDSL.kt
  src/main/kotlin/com/beside/daldal/domain/review/repository/CustomReviewDSLImpl.kt
  src/main/kotlin/com/beside/daldal/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/beside/daldal/domain/review/service/ReviewService.kt
Labels: enhancement

#16 fix : comment domain
  src/main/kotlin/com/beside/daldal/domain/comment/controller/CommentController.kt
  src/main/kotlin/com/beside/daldal/domain/comment/dto/CommentDTO.kt
  src/main/kotlin/com/beside/daldal/domain/comment/repository/CommentRepository.kt
  src/main/kotlin/com/beside/daldal/domain/comment/service/CommentService.kt
  src/main/kotlin/com/beside/daldal/domain/review/dto/ReviewReadDTO.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/Review.kt
  src/main/kotlin/com/beside/daldal/domain/review/service/ReviewService.kt
Labels: enhancement

#18 수정, 삭제와 관련해서 사용자 권한 문제 해결
  src/main/kotlin/com/beside/daldal/domain/course/controller/CourseController.kt
  src/main/kotlin/com/beside/daldal/domain/course/dto/CourseUpdateDTO.kt
  src/main/kotlin/com/beside/daldal/domain/course/service/CourseService.kt
  src/main/kotlin/com/beside/daldal/domain/member/service/MemberService.kt
  src/main/kotlin/com/beside/daldal/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/beside/daldal/domain/review/service/ReviewService.kt
Labels: bug, enhancement

#25 CORS 문제 해결
  docker-compose.yml
  src/main/kotlin/com/beside/daldal/config/SecurityConfig.kt
  src/main/kotlin/com/beside/daldal/config/WebConfig.kt
  src/main/kotlin/com/beside/daldal/domain/auth/controller/AuthController.kt
  src/main/kotlin/com/beside/daldal/jwt/JwtFilter.kt
Labels: bug, fix

#27 리뷰 수정 API에서 이미지 파일을 보내지 않는 경우 기존의 이미지를 사용하도록 수정 및 이미지 삭제 버그 수정
  src/main/kotlin/com/beside/daldal/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/beside/daldal/domain/review/entity/Review.kt
  src/main/kotlin/com/beside/daldal/domain/review/service/ReviewService.kt
Labels: bug, enhancement
